### ISSUE TITLE
Downloads for previous version?

### ISSUE THREAD

**Issue by ephraim71** [mathworks/Modeling-TVCd-Rocket-in-Simulink#1]
I have Matlab2020a, and when I try to run, it says "created using 2020b. To run this, open 2020b and click save -> export model to -> previous version"      
If you have the time, would appreciate if you posted the files for previous version. 
Or is there a workaround for this?
Thanks.

**Comment by connelld92** [comment]
Hi @Sgt-Miller ,

I just added v1.0.1 with files compatible with R2019a and later, hope this helps! - https://github.com/mathworks/Modeling-TVCd-Rocket-in-Simulink/releases/tag/v1.0.1 

Best,
Connell
